In [1]:
import numpy as np

In [2]:
a = [2,4,5,6]
type(a)

list

In [4]:
type(np.array(a))

numpy.ndarray

In [7]:
v = np.array([[2,3,4,5],[3,6,8,9]])

In [8]:
v

array([[2, 3, 4, 5],
       [3, 6, 8, 9]])

In [9]:
v[0][0]

2

In [10]:
v.shape

(2, 4)

In [14]:
np.array([4,5,6,7], ndmin=20)

array([[[[[[[[[[[[[[[[[[[[4, 5, 6, 7]]]]]]]]]]]]]]]]]]]])

In [17]:
np.array([4,5,6,7], dtype= complex)

array([4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j])

In [19]:
n = np.array([(3,4), (5,6)])

In [20]:
n

array([[3, 4],
       [5, 6]])

In [22]:
type(n[0][0])

numpy.int32

In [23]:
m = np.mat([5,8,9,2])

In [24]:
m

matrix([[5, 8, 9, 2]])

In [25]:
a = np.array(m)

array([[5, 8, 9, 2]])

In [26]:
m

matrix([[5, 8, 9, 2]])

In [27]:
np.asanyarray(m)

matrix([[5, 8, 9, 2]])

In [28]:
a = np.array([2,3,5,6])

In [29]:
b = a #shallow copy

In [30]:
b

array([2, 3, 5, 6])

In [31]:
b[0] = 12

In [32]:
b

array([12,  3,  5,  6])

In [33]:
a

array([12,  3,  5,  6])

In [34]:
c = np.copy(a) #deep copy

In [35]:
c

array([12,  3,  5,  6])

In [36]:
c[2] = 15

In [37]:
c

array([12,  3, 15,  6])

In [38]:
a

array([12,  3,  5,  6])

In [39]:
np.fromfunction(lambda x,y : x==y, (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [40]:
np.fromfunction(lambda x,y : x+y, (3,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.]])

In [46]:
np.fromstring('6,8', dtype = int, sep=',')

array([6, 8])

In [47]:
a = [[3,4,5], [5,6,8], [1,7,9]]

In [55]:
n = np.array(a)

In [56]:
n

array([[3, 4, 5],
       [5, 6, 8],
       [1, 7, 9]])

In [57]:
n.ndim

2

In [58]:
n.size

9

In [59]:
n.shape

(3, 3)

In [60]:
n.dtype

dtype('int32')

In [63]:
range(5.3,12.5)

TypeError: 'float' object cannot be interpreted as an integer

In [67]:
n = np.arange(5.4, 20.7, 0.5)

In [68]:
list(n)

[5.4,
 5.9,
 6.4,
 6.9,
 7.4,
 7.9,
 8.4,
 8.9,
 9.4,
 9.9,
 10.4,
 10.9,
 11.4,
 11.9,
 12.4,
 12.9,
 13.4,
 13.9,
 14.4,
 14.9,
 15.4,
 15.9,
 16.4,
 16.9,
 17.4,
 17.9,
 18.4,
 18.9,
 19.4,
 19.9,
 20.4]

In [80]:
np.linspace(2, 10, 20, retstep=True )

(array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
         4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
         6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
         8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ]),
 0.42105263157894735)

In [83]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [86]:
np.ones((3,4)) + 5 #broadcasting

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [87]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
np.logspace(5.6, 9.8, 6, base=2)

array([ 48.50293013,  86.82267696, 155.4169452 , 278.20412481,
       497.99933308, 891.44377682])

In [93]:
np.random.rand(4,5) #uniform distribution

array([[0.5458244 , 0.06034561, 0.13002411, 0.24168951, 0.61040705],
       [0.75618908, 0.67527927, 0.88577364, 0.92290846, 0.90331998],
       [0.89968939, 0.40661848, 0.04011881, 0.73384765, 0.01645379],
       [0.72219497, 0.17297849, 0.16152754, 0.95417315, 0.06058578]])

In [94]:
np.random.randn(4,5) #standard normal distribution

array([[-0.26612788,  1.57490481,  1.48772465,  0.54804336, -1.07990763],
       [ 1.66280878, -0.2083932 ,  0.93909591, -1.30628106, -1.4270145 ],
       [-0.56145705,  1.44135937,  2.30020685, -1.0852343 , -0.8467834 ],
       [-1.0868155 ,  0.14609248,  0.10975545,  0.31767677, -0.97757   ]])

In [97]:
n = np.random.randint(2,8, (4,5))

In [100]:
n

array([[7, 6, 2, 4, 5],
       [6, 2, 4, 2, 6],
       [4, 2, 6, 4, 5],
       [4, 3, 3, 6, 2]])

In [99]:
n[0:2,0:2]

array([[7, 6],
       [6, 2]])

In [101]:
n[0:2, 3:5]

array([[4, 5],
       [2, 6]])

In [102]:
n[2:4,2:4]

array([[6, 4],
       [3, 6]])

In [103]:
n>4

array([[ True,  True, False, False,  True],
       [ True, False, False, False,  True],
       [False, False,  True, False,  True],
       [False, False, False,  True, False]])

In [104]:
n[n>4]

array([7, 6, 5, 6, 6, 6, 5, 6])

In [105]:
m = np.array([[4,5,6], [5,8,9]])

In [106]:
m

array([[4, 5, 6],
       [5, 8, 9]])

In [107]:
n = np.array([[2,3,7], [1,4,9]])

In [118]:
t = n.T #transpose

In [109]:
m+n

array([[ 6,  8, 13],
       [ 6, 12, 18]])

In [110]:
m-n

array([[ 2,  2, -1],
       [ 4,  4,  0]])

In [111]:
m*n

array([[ 8, 15, 42],
       [ 5, 32, 81]])

In [119]:
m@t

array([[ 65,  78],
       [ 97, 118]])

In [113]:
m1 = np.array([[0,1], [2,3]])

In [114]:
m2 = np.array([[2,3], [1,8]])

In [115]:
m1*m2

array([[ 0,  3],
       [ 2, 24]])

In [116]:
m1@m2

array([[ 1,  8],
       [ 7, 30]])

In [120]:
m1**2

array([[0, 1],
       [4, 9]], dtype=int32)

In [121]:
pow(m1,3)

array([[ 0,  1],
       [ 8, 27]], dtype=int32)

In [123]:
np.random.rand(4,5).reshape(10,2) #reshaping

array([[0.40021433, 0.13291534],
       [0.65172134, 0.0748543 ],
       [0.53987454, 0.50710804],
       [0.76304955, 0.22155758],
       [0.42411148, 0.35165633],
       [0.86061023, 0.57421165],
       [0.36688775, 0.33422127],
       [0.79272593, 0.11864474],
       [0.69214863, 0.2776901 ],
       [0.03390406, 0.50299641]])

In [124]:
np.sqrt(m1)

array([[0.        , 1.        ],
       [1.41421356, 1.73205081]])

In [125]:
np.exp(m1)

array([[ 1.        ,  2.71828183],
       [ 7.3890561 , 20.08553692]])